# Generated by Django 5.2.1 on 2025-05-16 14:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(max_length=50, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='تصویر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('product_count', models.PositiveIntegerField(default=0, verbose_name='تعداد محصولات')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر اصلی')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='فروش رفته')),
                ('badge', models.CharField(choices=[('none', 'بدون نشان'), ('sale', 'تخفیف'), ('new', 'جدید'), ('hot', 'پیشنهاد ویژه'), ('bestseller', 'پرفروش'), ('limited', 'محدود')], default='none', max_length=20, verbose_name='نشان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازدهی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
